version: '3.7'

services:
  backend:
    build: .
    command: bash -c "python manage.py flush --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks: ['mynetwork']
    hostname: backend
  frontend:
    build: ./frontend
    volumes:
        - ./frontend:/app
        - /app/node_modules
    ports:
        - "3000:3000"
    environment:
        - NODE_ENV=development
    links:
      - backend:backend
    networks: ['mynetwork']
    command: yarn --cwd tienda-app/ start
    
networks: {mynetwork: {}}