language: python

python:
  - 3.7

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install -q coveralls
 
before_script:

script:
 - python tienda/manage.py test

after_script:
 - coveralls
