language: python

python:
  - 3.7

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install -q coveralls
 
before_script:
 - python tienda/manage.py makemigrations
 - python tienda/manage.py migrate
 - python tienda/manage.py runserver &

script:
 -  coverage run --source='.' tienda/manage.py test

after_script:
 - coveralls
