# Generated by Django 3.0.3 on 2020-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0002_auto_20200211_1323'),
        ('productos', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('subinventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
            ],
            options={
                'verbose_name': 'ProductoOrden',
                'verbose_name_plural': 'ProductoOrdens',
            },
        ),
    ]
