# Generated by Django 3.0.3 on 2020-02-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_auto_20200211_1323'),
        ('productos', '0002_producto_descripcion'),
        ('ordenescompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='LISTO', max_length=50)),
                ('subinventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.AddField(
            model_name='productoorden',
            name='folio',
            field=models.IntegerField(default=10000000001),
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenescompra.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'OrdenProducto',
                'verbose_name_plural': 'OrdenProductos',
            },
        ),
    ]
