# Generated by Django 3.0.3 on 2020-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='id',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='subinventario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
